services:
  hammerdb:
    image: tpcorg/hammerdb
    container_name: hammerdb
    tty: true
    stdin_open: true
    # Use host networking alongside ssh tunnel to the database server for a persistent connection.
    network_mode: host
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    
    env_file:
      - ./configs/butler_prod_ssh.env
